Parcel broke again with weird error
Build failed.

@parcel/transformer-js: (0 , _native.transform) is not a function

  TypeError: (0 , _native.transform) is not a function
      at Object.transform (/Users/josedmartinez/Documents/CODE CAREER
  FOUNDRY/OTHER
  PROJECTS/myFaveFlixes6-client/node_modules/@parcel/transformer-js/lib/JSTransformer.js:378:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Transformation.runTransformer
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:653:5)
      at async Transformation.runPipeline
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:402:36)
      at async Transformation.runPipelines
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:265:40)
      at async Transformation.run
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:183:21)
      at async Object.run
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/requests/AssetRequest.js:122:7)
      at async RequestTracker.runRequest
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async AssetGraphBuilder.runAssetRequest
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:857:18)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn
  (/Users/josedmartinez/.nvm/versions/node/v16.16.0/lib/node_modules/parcel/node_modules/@parcel/utils/lib/index.js:33579:13)